---
apiVersion: v1
kind: Namespace
metadata:
  name: encryptah
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: encryptah-frontend
  namespace: encryptah
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: encryptah-backend
  namespace: encryptah
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: encryptah
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-tags: encryptah
      labels:
        app: backend
    spec:
      containers:
        - name: encryptah-backend
          image: jacobmammoliti/encryptah-backend:1.0
          ports:
            - containerPort: 5678
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 5678
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 5678
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
      serviceAccountName: encryptah-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    version: v1
  name: frontend-v1
  namespace: encryptah
spec:
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: encryptah-backend:5678
        consul.hashicorp.com/service-meta-version: v1
        consul.hashicorp.com/service-tags: encryptah
      labels:
        app: frontend
        version: v1
    spec:
      containers:
        - name: encryptah-frontend
          image: jacobmammoliti/encryptah-frontend:1.0
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: BACKEND_HOSTNAME
              value: 127.0.0.1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
      serviceAccountName: encryptah-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    version: v2
  name: frontend-v2
  namespace: encryptah
spec:
  selector:
    matchLabels:
      app: frontend
      version: v2
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: encryptah-backend:5678
        consul.hashicorp.com/service-meta-version: v2
        consul.hashicorp.com/service-tags: encryptah
      labels:
        app: frontend
        version: v2
    spec:
      containers:
        - name: encryptah-frontend
          image: jacobmammoliti/encryptah-frontend:2.0
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: BACKEND_HOSTNAME
              value: 127.0.0.1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
      serviceAccountName: encryptah-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: encryptah
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: encryptah
spec:
  ports:
  - port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    app: backend